# Generated by Django 5.2.9 on 2026-02-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
